authoritydir: ../config/testdir
staticdir: ../config/testdir
authentication-authority: granting
servertls: granting   # don't do this in production please

staticfiles:
  - testa.txt

authorities:
  granting:
    type: TLS
    key: selfsig.key
    cert: selfsig.pem

groups:
  admins:
  servers:

accounts:
  - principal: my-admin
    group: admins
  - principal: my-server
    group: servers

grants:
  test-1:
    privilege: construct-configuration
    group: servers
    contents: "and now, there will be cake"
  test-2:
    privilege: bootstrap-account
    group: admins
    scope: servers
    lifespan: 5m
