# THIS IS JUST AN EXAMPLE -- THE ACTUAL CONFIGURATION IS GENERATED DURING DEPLOYMENT, AND NOT FROM THIS

keyserver: egg-sandwich.mit.edu:20557
authoritypath: /etc/homeworld/keyclient/keyservertls.pem

keypath: /etc/homeworld/keyclient/granting.key
certpath: /etc/homeworld/keyclient/granting.pem

tokenpath: /etc/homeworld/keyclient/bootstrap_token.txt
tokenapi: renew-keygrant

downloads:
  - type: authority
    name: etcd-client
    path: /etc/homeworld/authorities/etcd-client.pem
    refresh: 24h
    mode: 644

  - type: authority
    name: etcd-server
    path: /etc/homeworld/authorities/etcd-server.pem
    refresh: 24h
    mode: 644

  - type: authority
    name: kubernetes
    path: /etc/homeworld/authorities/kubernetes.pem
    refresh: 24h
    mode: 644

  - type: authority
    name: ssh-user
    path: /etc/ssh/ssh_user_ca.pub
    refresh: 168h   # allow a week for mistakes to be noticed on this one
    mode: 644

  - type: static
    name: cluster.conf
    path: /etc/homeworld/cluster.conf
    refresh: 24h
    mode: 644

  - type: api
    name: get-local-config
    path: /etc/homeworld/local.conf
    refresh: 24h
    mode: 644

  # just for master nodes

  - type: authority
    name: serviceaccount
    path: /etc/homeworld/keys/serviceaccount.pem
    refresh: 24h
    mode: 644

  - type: api
    name: fetch-serviceaccount-key
    path: /etc/homeworld/keys/serviceaccount.key
    refresh: 24h
    mode: 600

keys:
  - name: keygranting
    type: tls
    key: /etc/homeworld/keyclient/granting.key
    cert: /etc/homeworld/keyclient/granting.pem
    api: renew-keygrant
    in-advance: 336h   # renew two weeks before expiration

  - name: ssh-host
    type: ssh-pubkey
    key: /etc/ssh/ssh_host_rsa_key.pub
    cert: /etc/ssh/ssh_host_rsa_cert
    api: grant-ssh-host
    in-advance: 168h   # renew one week before expiration

  # NOTE: THIS PART WILL VARY BY SERVER

  - name: kube-worker
    type: tls
    key: /etc/homeworld/keys/kubernetes-worker.key
    cert: /etc/homeworld/keys/kubernetes-worker.pem
    api: grant-kubernetes-worker
    in-advance: 168h   # renew one week before expiration

  - name: kube-master
    type: tls
    key: /etc/homeworld/keys/kubernetes-master.key
    cert: /etc/homeworld/keys/kubernetes-master.pem
    api: grant-kubernetes-master
    in-advance: 168h   # renew one week before expiration

  - name: etcd-server
    type: tls
    key: /etc/homeworld/keys/etcd-server.key
    cert: /etc/homeworld/keys/etcd-server.pem
    api: grant-etcd-server
    in-advance: 168h   # renew one week before expiration

  - name: etcd-client
    type: tls
    key: /etc/homeworld/keys/etcd-client.key
    cert: /etc/homeworld/keys/etcd-client.pem
    api: grant-etcd-client
    in-advance: 168h   # renew one week before expiration
