# stored in /etc/hyades/keyserver/keyserver.conf

authoritydir: /etc/hyades/keyserver/authorities/
staticdir: /etc/hyades/keyserver/static/
authentication-authority: keygranting
servertls: servertls

staticfiles:
  - cluster.conf

authorities:
  keygranting:
    type: TLS
    key: keygrant.key
    cert: keygrant.pem

  servertls:
    type: TLS
    key: server.key
    cert: server.pem

  ssh-user:
    type: SSH
    key: ssh_user_ca
    cert: ssh_user_ca.pub

  ssh-host:
    type: SSH
    key: ssh_host_ca
    cert: ssh_host_ca.pub

  etcd-server:
    type: TLS
    key: etcd-server.key
    cert: etcd-server.pem

  etcd-client:
    type: TLS
    key: etcd-client.key
    cert: etcd-client.pem

  kubernetes:
    type: TLS
    key: kubernetes.key
    cert: kubernetes.pem

  serviceaccount:
    type: static
    key: serviceaccount.key
    cert: serviceaccount.pem

accounts:
  - principal: eggs-benedict.mit.edu
    group: master-nodes
    limit-ip: true
    metadata:
      ip: 18.181.0.97
      hostname: eggs-benedict
      schedule: false

  - principal: huevos-rancheros.mit.edu
    group: master-nodes
    limit-ip: true
    metadata:
      ip: 18.181.0.104
      hostname: huevos-rancheros
      schedule: false

  - principal: ole-miss.mit.edu
    group: master-nodes
    limit-ip: true
    metadata:
      ip: 18.181.0.106
      hostname: ole-miss
      schedule: false

  - principal: grilled-cheese.mit.edu
    group: worker-nodes
    limit-ip: true
    metadata:
      ip: 18.181.0.128
      hostname: grilled-cheese
      schedule: true

  - principal: avocado-burger.mit.edu
    group: worker-nodes
    limit-ip: true
    metadata:
      ip: 18.181.0.129
      hostname: avocado-burger
      schedule: true

  - principal: french-toast.mit.edu
    group: worker-nodes
    limit-ip: true
    metadata:
      ip: 18.181.2.232
      hostname: french-toast
      schedule: true

  - principal: egg-sandwich.mit.edu
    group: supervisor-nodes
    limit-ip: true
    metadata:
      ip: 18.181.0.253
      hostname: egg-sandwich
      schedule: false

  - principal: cela@ATHENA.MIT.EDU
    disable-direct-auth: true
    group: root-admins

  - principal: dukhovni@ATHENA.MIT.EDU
    disable-direct-auth: true
    group: root-admins

  - principal: ikdc@ATHENA.MIT.EDU
    disable-direct-auth: true
    group: root-admins

groups:
  root-admins:
  nodes:
  supervisor-nodes:
    subgroupof: nodes
  kubernetes-nodes:
    subgroupof: nodes
  worker-nodes:
    subgroupof: kubernetes-nodes
  master-nodes:
    subgroupof: master-nodes

grants:

  # ADMIN ACCESS TO THE RUNNING CLUSTER

  access-ssh:
    group: root-admins
    privilege: sign-ssh
    authority: ssh-user
    lifespan: 4h
    ishost: false
    common-name: temporary-ssh-grant-(principal)
    allowed-names:
    - root

  access-etcd:
    group: root-admins
    privilege: sign-tls
    authority: etcd-client
    lifespan: 4h
    ishost: false
    common-name: temporary-etcd-grant-(principal)

  access-kubernetes:
    group: root-admins
    privilege: sign-tls
    authority: kubernetes
    lifespan: 4h
    ishost: false
    common-name: temporary-kube-grant-(principal)

  # MEMBERSHIP IN THE CLUSTER

  bootstrap:
    group: root-admins
    privilege: bootstrap-account
    scope: nodes
    lifespan: 1h

  renew-keygrant:
    group: nodes
    privilege: sign-tls
    authority: keygranting
    lifespan: 960h  # fourty day lifespan
    ishost: false
    common-name: (principal)

  auth-to-kerberos:
    group: supervisor-nodes
    privilege: impersonate
    scope: root-admins

  # CONFIGURATION ENDPOINT

  get-local-config:
    group: nodes
    privilege: construct-configuration
    contents: |
      # generated automatically by keyserver
      HOST_NODE=(hostname)
      HOST_DNS=(hostname).mit.edu
      HOST_IP=(ip)
      SCHEDULE_WORK=(schedule)

  # SERVER CERTIFICATES

  grant-ssh-host:
    group: nodes
    privilege: sign-ssh
    authority: ssh-host
    lifespan: 1440h  # sixty day lifespan
    ishost: true
    common-name: admitted-(principal)
    allowed-names:
    - (hostname).mit.edu
    - (hostname)
    - (ip)

  grant-kubernetes-master:
    group: master-nodes
    privilege: sign-tls
    authority: kubernetes
    lifespan: 720h  # thirty day lifespan
    ishost: true
    common-name: kube-master-(hostname)
    allowed-names:
    - (hostname).mit.edu
    - (hostname)
    - kubernetes
    - kubernetes.default
    - kubernetes.default.svc
    - kubernetes.default.svc.hyades.local
    - (ip)
    - 172.28.0.1

  grant-etcd-server:
    group: master-nodes
    privilege: sign-tls
    authority: etcd-server
    lifespan: 720h  # thirty day lifespan
    ishost: true
    common-name: etcd-server-(hostname)
    allowed-names:
    - (hostname).mit.edu
    - (hostname)
    - (ip)

  # CLIENT CERTIFICATES

  grant-kubernetes-worker:
    group: kubernetes-nodes
    privilege: sign-tls
    authority: kubernetes
    lifespan: 720h  # thirty day lifespan
    ishost: false
    common-name: kube-worker-(hostname)
    allowed-names:
    - (hostname).mit.edu
    - (hostname)
    - (ip)

  grant-etcd-client:
    group: master-nodes
    privilege: sign-tls
    authority: etcd-client
    lifespan: 720h  # thirty day lifespan
    ishost: false
    common-name: etcd-client-(hostname)
    allowed-names:
    - (hostname).mit.edu
    - (hostname)
    - (ip)

  fetch-serviceaccount-key:
    group: master-nodes
    privilege: fetch-key
    authority: serviceaccount
