control:
  name: homeworld-prometheus
  version: 2.0.0-4
  date: 2018-01-29T17:17:23-0500
  type: deb

build:
  - type: upstream-extract
    upstream: promu-%.tar.xz
    version: sipb-0.1.1
    focus: promu-%
    stage: go/src/github.com/prometheus/promu

  - type: upstream-extract
    upstream: prometheus-%.tar.xz
    version: 2.0.0
    focus: prometheus-%
    stage: go/src/github.com/prometheus/prometheus

  # TODO: abstract away the go-prepare + bash (GOROOT, PATH) pattern
  - type: go-prepare
    version: 1.9.3
    stage: goroot

  - type: bash
    code: |
      export GOROOT="${STAGE}/goroot"
      export GOPATH="${STAGE}/go"
      export PATH="${GOROOT}/bin:${GOPATH}/bin:${PATH}"

      go install github.com/prometheus/promu

      mkdir bin
      cd go/src/github.com/prometheus/prometheus && promu build --prefix="${STAGE}/bin"

  - type: copy
    stage: bin
    output: /usr/bin/
    recursive: true

  - type: copy
    input: prometheus.service
    output: /usr/lib/systemd/system/prometheus.service
