keyserver: localhost
authoritypath: ../testdir/keyclient/keyservertls.pem

keypath: ../testdir/keyclient/granting.key
certpath: ../testdir/keyclient/granting.pem

tokenpath: ../testdir/keyclient/bootstrap_token.txt
tokenapi: renew-keygrant
downloads:
  - type: authority
    name: etcd-client
    path: ../testdir/authorities/etcd-client.pem
    refresh: 24h
    mode: 644

keys:
  - name: keygranting
    type: tls
    key: ../testdir/keyclient/granting.key
    cert: ../testdir/keyclient/granting.pem
    api: renew-keygrant
    in-advance: 336h   # renew two weeks before expiration

broken: test