authoritydir: ../config/testdir
staticdir: ../config/testdir
authentication-authority: granting
servertls: granting   # don't do this in production please

staticfiles:
  - testa.txt

authorities:
  granting:
    type: TLS
    key: test1.key
    cert: test1.pem

groups:
  admins:

accounts:
  - principal: my-admin
    group: admins
    disable-direct-auth: true

grants:
  test-1:
    privilege: construct-configuration
    group: admins
    contents: "this is a test!"
