---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-state-metrics
  namespace: kube-system
---
apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  namespace: kube-system
  labels:
    app: kube-state-metrics
spec:
  selector:
    app: kube-state-metrics
  ports:
  - name: metrics
    port: 80
    protocol: TCP
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-state-metrics
  namespace: kube-system
  labels:
    app: kube-state-metrics
    version: v1.2.0-1
spec:
  replicas: 1
  selector:
    app: kube-state-metrics
    version: v1.2.0-1
  template:
    metadata:
      labels:
        app: kube-state-metrics
        version: v1.2.0-1
      annotations:
        homeworld.mit.edu/unsupported-fetch-info: aci
    spec:
      serviceAccountName: kube-state-metrics
      containers:
      - name: kube-kube-state-metrics
        image: homeworld.mit.edu/kube-state-metrics:1.2.0-1
        resources:
          limits:
            memory: 150Mi
          requests:
            cpu: 100m
            memory: 50Mi
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
