groups:
- name: recording
  rules:
  - record: verify_dns_addon_run
    expr: sum(kube_replicationcontroller_status_ready_replicas{replicationcontroller="kube-dns-v20"}) >= bool sum(kube_replicationcontroller_spec_replicas{replicationcontroller="kube-dns-v20"}) - 1
  - record: verify_dns_addon_deploy
    expr: sum(kube_replicationcontroller_spec_replicas{replicationcontroller="kube-dns-v20"}) >= bool 1
  - record: verify_dns_addon_query
    expr: (avg(dns_lookup_internal_check) >= bool 1) and (time() - min(dns_lookup_recency) <= bool 30)
  - record: verify_dns_all
    expr: verify_dns_addon_run and verify_dns_addon_deploy and verify_dns_addon_query

  - record: verify_flannel_run
    expr: sum(kube_daemonset_status_number_ready{daemonset="kube-flannel-ds"}) == bool sum(kube_node_info)
  - record: verify_flannel_monitor_meta
    expr: (sum(flannel_collect_enum_check) == bool 1) and (sum(flannel_collect_enum_dup_check) == bool 1)
  - record: verify_flannel_monitor
    expr: (sum(flannel_collect_check) == bool sum(kube_node_info)) and (sum(flannel_duplicate_check) == bool sum(kube_node_info)) and (sum(flannel_monitor_check) == bool sum(kube_node_info)) and (time() - min(flannel_monitor_recency) <= bool 60)
  - record: verify_flannel_talk
    expr: (sum(flannel_talk_check) == bool sum(kube_node_info) * sum(kube_node_info)) and (count(flannel_talk_check) == bool sum(kube_node_info) * sum(kube_node_info))
  - record: verify_flannel_all
    expr: verify_flannel_run and verify_flannel_monitor_meta and verify_flannel_monitor and verify_flannel_talk

  - record: verify_aci_pull
    expr: sum(aci_pull_check) == bool sum(kube_node_info)
  - record: verify_aci_run
    expr: sum(aci_rkt_check) == bool sum(kube_node_info)
  - record: verify_aci_all
    expr: verify_aci_pull and verify_aci_run

  - record: verify_kube_apiservers_up
    expr: sum(up{job="kubernetes-apiservers"}) == bool 3
  - record: verify_kube_nodes_registered
    expr: sum(kube_node_info) == bool count(up{job="node-resources"}) - 1
  - record: verify_kube_up_to_date
    expr: sum(kube_node_info{kubelet_version=~"v{{REGEXVER}}+.*",kubeproxy_version=~"v{{REGEXVER}}+.*"}) == bool sum(kube_node_info)
  - record: verify_kube_nodes_schedulable
    expr: (sum(kube_node_spec_unschedulable{node=~"{{REGEXNODES}}"}) == bool 3) and (sum(kube_node_spec_unschedulable) == bool 3)
  - record: verify_kube_nodes_ready
    expr: sum(kube_node_status_condition{condition="Ready",status="true"}) == bool sum(kube_node_info)
  - record: verify_kube_namespaces
    expr: sum(kube_namespace_status_phase{phase="Active",namespace=~"default|kube-public|kube-system"}) == bool 3
  - record: verify_kube_all
    expr: verify_kube_apiservers_up and verify_kube_nodes_registered and verify_kube_up_to_date and verify_kube_nodes_schedulable and verify_kube_nodes_ready and verify_kube_namespaces

  - record: verify_etcd_all_online
    expr: sum(etcd_server_has_leader) == bool 3
  - record: verify_etcd_in_use
    expr: sum(rate(etcd_server_proposals_committed_total[1m])) >= bool 1
  - record: verify_etcd_all
    expr: verify_etcd_all_online and verify_etcd_in_use

  - record: verify_infra_nodes_online
    expr: sum(up{job="node-resources"}) == bool count(up{job="node-resources"})
  - record: verify_infra_nodes_accessible
    expr: sum(keysystem_ssh_access_check) == bool count(up{job="node-resources"})
