---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flannel-monitor
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-flannel-monitor-reflector-ds
  namespace: kube-system
  labels:
    tier: node
    app: flannel-monitor-reflector
spec:
  template:
    metadata:
      labels:
        tier: node
        app: flannel-monitor-reflector
      annotations:
        homeworld.mit.edu/unsupported-fetch-info: aci
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      serviceAccountName: flannel-monitor
      containers:
      - name: kube-flannel-monitor
        image: homeworld.private/flannel-monitor:0.1.9
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: FLANNEL_NETWORK
          value: "{{NETWORK}}"
        resources:
          limits:
            memory: 150Mi
          requests:
            cpu: 100m
            memory: 50Mi
        command: [ "/usr/bin/flannel-monitor-reflector" ]
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-flannel-monitor-ds
  namespace: kube-system
  labels:
    tier: node
    app: flannel-monitor
spec:
  template:
    metadata:
      labels:
        tier: node
        app: flannel-monitor
      annotations:
        homeworld.mit.edu/unsupported-fetch-info: aci
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      serviceAccountName: flannel-monitor
      containers:
      - name: kube-flannel-monitor
        image: homeworld.private/flannel-monitor:0.1.9
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          limits:
            memory: 150Mi
          requests:
            cpu: 100m
            memory: 50Mi
        command: [ "/usr/bin/flannel-monitor" ]
---
apiVersion: v1
kind: Service
metadata:
  name: flannel-monitor-collector
  namespace: kube-system
  labels:
    app: flannel-monitor-collector
spec:
  selector:
    app: flannel-monitor-collector
  ports:
  - name: metrics
    port: 80
    protocol: TCP
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: flannel-monitor-collector
  namespace: kube-system
  labels:
    app: flannel-monitor-collector
    version: v0.1.7
spec:
  replicas: 1
  selector:
    app: flannel-monitor-collector
    version: v0.1.7
  template:
    metadata:
      labels:
        app: flannel-monitor-collector
        version: v0.1.7
      annotations:
        homeworld.mit.edu/unsupported-fetch-info: aci
    spec:
      serviceAccountName: flannel-monitor
      containers:
      - name: kube-flannel-monitor
        image: homeworld.private/flannel-monitor:0.1.9
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        command: [ "/usr/bin/flannel-monitor-collector" ]
        resources:
          limits:
            memory: 150Mi
          requests:
            cpu: 100m
            memory: 50Mi
        ports:
        - containerPort: 80
          name: metrics
          protocol: TCP
